/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_pthread_PosixUtils */

#ifndef _Included_com_example_ndk_pthread_PosixUtils
#define _Included_com_example_ndk_pthread_PosixUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_pthread_PosixUtils
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1pthread_PosixUtils_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_pthread_PosixUtils
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1pthread_PosixUtils_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_pthread_PosixUtils
 * Method:    pthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1pthread_PosixUtils_pthread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
