/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_pthread_UUIDUtils */

#ifndef _Included_com_example_ndk_pthread_UUIDUtils
#define _Included_com_example_ndk_pthread_UUIDUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
